version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2024.01.1
    working_directory: ~/repo/event-buffer
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew check

workflows:
  test:
    jobs:
      - build