version: 2.1

orbs:
  codecov: codecov/codecov@5.4.3

jobs:
  build:
    docker:
      - image: cimg/android:2025.04.1
    working_directory: ~/repo/event-buffer
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew check
      - run: ./gradlew koverXmlReport
      - codecov/upload

workflows:
  test:
    jobs:
      - build